---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Restart MaaS
  hosts: "{{ maas_restart_on_host_override | default('maas_restart_on_host') }}"
  gather_facts: false
  tasks:
    - name: Restart rackspace-monitoring-poller (systemd)
      service:
        name: rackspace-monitoring-poller.systemd.service
        state: restarted
        sleep: 10
      register: _maas_poller_restart
      until: _maas_poller_restart | success
      retries: 3
      delay: 2
      when:
        - maas_private_monitoring_enabled | bool
        - physical_host in groups['shared-infra_hosts']
        - maas_restart_independent | default(true) | bool or
          maas_force_restart | default(false) | bool
        - ansible_distribution_version == "16.04"

    - name: Restart rackspace-monitoring-poller (upstart)
      service:
        name: rackspace-monitoring-poller
        state: restarted
        sleep: 10
      register: _maas_poller_restart
      until: _maas_poller_restart | success
      retries: 3
      delay: 2
      when:
        - maas_private_monitoring_enabled | bool
        - physical_host in groups['shared-infra_hosts']
        - maas_restart_independent | default(true) | bool or
          maas_force_restart | default(false) | bool
        - ansible_distribution_version == "14.04"

    - name: Restart rackspace-monitoring-agent
      service:
        name: rackspace-monitoring-agent
        state: restarted
      register: _maas_agent_restart
      until: _maas_agent_restart | success
      retries: 3
      delay: 2
      failed_when: false
      when: >
        maas_restart_independent | default(true) | bool or
        maas_force_restart | default(false) | bool

    - name: debug _maas_agent_restart
      command: "systemctl status rackspace-monitoring-agent.service"
      failed_when: false
      register: systemctl_raxmon

    - name: debug journalctl
      command: "journalctl -xe"
      failed_when: false
      register: journal_raxmon

    - name: print monitoring-config
      command: "cat /etc/rackspace-monitoring-agent.cfg"
      failed_when: false
      register: raxmon_config

    - name: print .raxrc
      command: "cat ~/.raxrc"
      failed_when: false
      register: raxrc_config

    - name: Debug vars
      debug:
        var: "{{ item }}"
      with_items:
        - raxrc_config
        - raxmon_config
        - journal_raxmon
        - systemctl_raxmon
        - _maas_agent_restart

  vars_files:
    - vars/main.yml
  tags:
    - maas-restart
